# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 580417339d03a0b26456e7f52829580a985d832283a085f931661ba7215b211b6894471cc8a4a68101853db0b341d1f1f62505b7644b8b13b781b0535e021c43

test:
  secret_key_base: 9c3fa5d367648a5782ee6e468784dd9ca49b5dd8844107713b3bc19b055fddd8a5e5aee605f038ca8244fb6efa37bf48a3c9ec575f944de659a6aa520df3ea5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
